export const NAV = [
  { to: '/', label: 'Dashboard', icon: '📊', roles: [] },
  { to: '/enquiries', label: 'Enquiries', icon: '📝', roles: [] },
  { to: '/follow-ups', label: 'Follow-Ups', icon: '⏰', roles: [] },
  { to: '/rooms', label: 'Rooms', icon: '🚪', roles: [] },
  { to: '/availability', label: 'Availability', icon: '📅', roles: [] },
  { to: '/bookings', label: 'Bookings', icon: '🧾', roles: [] },
  { to: '/self-checkins', label: 'Self Check-in', icon: '🪪', roles: [] },
  { to: '/room-service', label: 'Room Service', icon: '🛎️', roles: [] },
  { to: '/housekeeping', label: 'Housekeeping', icon: '🧹', roles: [] },
  { to: '/feedback', label: 'Feedback', icon: '⭐', roles: [] },
  { to: '/complaints', label: 'Complaints', icon: '⚠️', roles: [] },
  { to: '/corporate', label: 'Corporate', icon: '🏢', roles: ['admin','manager','corporate_coordinator'] },
  { to: '/groups', label: 'Group Bookings', icon: '👥', roles: ['admin','manager','corporate_coordinator'] },
  { to: '/guests', label: 'Guests / Loyalty', icon: '🏅', roles: [] },
  { to: '/handovers', label: 'Shift Handover', icon: '🔁', roles: [] },
  { to: '/payments', label: 'Payments / GST', icon: '💰', roles: ['admin','manager','accounts','front_desk'] },
  { to: '/pricing', label: 'Seasonal Pricing', icon: '🏷️', roles: ['admin','manager'] },
  { to: '/reports', label: 'Reports', icon: '📈', roles: ['admin','manager','accounts'] },
  { to: '/users', label: 'Users', icon: '👤', roles: ['admin'] },
];
